INSERT INTO LOCKER (ID, CODE, STATUS, CREATE_AT)
VALUES (1L, 1L, TRUE, '2021-02-01');
INSERT INTO LOCKER (ID, CODE, STATUS, CREATE_AT)
VALUES (2L, 2L, TRUE, '2021-02-01');
INSERT INTO LOCKER (ID, CODE, STATUS, CREATE_AT)
VALUES (3L, 3L, TRUE, '2021-02-01');
INSERT INTO LOCKER (ID, CODE, STATUS, CREATE_AT)
VALUES (4L, 4L, TRUE, '2021-02-01');
INSERT INTO LOCKER (ID, CODE, STATUS, CREATE_AT)
VALUES (5L, 5L, TRUE, '2021-02-01');
INSERT INTO RECIPE (ID, RECIPE_ID, DESCRIPTION, OWNER, STATUS)
VALUES (1L, 1L, 'WITAMINA C', 'Tomek', true);
INSERT INTO RECIPE (ID, RECIPE_ID, DESCRIPTION, OWNER, STATUS)
VALUES (2L, 2L, 'GRIPEX', 'Mati', false);
INSERT INTO RECIPE (ID, RECIPE_ID, DESCRIPTION, OWNER, STATUS)
VALUES (3L, 3L,'APAP', 'Dawid', true);
INSERT INTO RECIPE (ID, RECIPE_ID, DESCRIPTION, OWNER, STATUS)
VALUES (4L, 4L, 'IBUPROM', 'Ola', false);
